export const SET_EVENT = 'SET_EVENT'
export const SET_EVENT_PRODUCTS = 'SET_EVENT_PRODUCTS'
export const ADD_EVENT_PRODUCTS_LIKED = 'ADD_EVENT_PRODUCTS_LIKED'
export const SET_EVENT_PRODUCTS_LIKED = 'SET_EVENT_PRODUCTS_LIKED'
