export const LIST_NOTIFICATION = 'LIST_NOTIFICATION'
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION'
export const RESET_NOTIFICATION = 'RESET_NOTIFICATION'
export const RESET_POPUP_NOTIFICATION = 'RESET_POPUP_NOTIFICATION'
